import 'dart:typed_data';

import 'package:sodium_libs/sodium_libs.dart';

import 'suite.dart';

/// The two symmetric keys an envelope needs, derived from K_file
/// according to the transfer's crypto suite.
///
/// Deriving here — at the boundary, before the primitives are called —
/// rather than teaching [FileCrypto] and [Envelope] about suites keeps
/// suite dispatch in exactly one place. Those classes encrypt with the
/// key they are handed and have no opinion about where it came from,
/// which is also why adding suite 2 changed no test call site.
///
/// **suite 1** hands K_file to both primitives unchanged. **suite 2**
/// derives a distinct subkey for each. Suite 1 is not known to be
/// breakable: `crypto_secretstream` derives its own subkey via
/// HChaCha20 from a random 24-byte header, and `crypto_secretbox`
/// (XSalsa20) derives one via HSalsa20 from a random 24-byte nonce, so
/// the same key never reaches the same function with the same input.
/// But that safety is an argument about primitive internals rather
/// than a property of our construction, and arguments like that are
/// what audits spend time on. Suite 2 removes the question.
class SuiteKeys {
  const SuiteKeys._({required this.headerKey, required this.bodyKey});

  /// Key for the `enc_header` secretbox.
  final Uint8List headerKey;

  /// Key for the file-body secretstream.
  final Uint8List bodyKey;

  /// libsodium requires exactly `crypto_kdf_CONTEXTBYTES` (8) bytes of
  /// context. It is a domain separator, not a secret.
  static const String kdfContext = 'opaqshar';

  static final BigInt _headerSubkeyId = BigInt.one;
  static final BigInt _bodySubkeyId = BigInt.two;

  /// Derive the pair for `suite`.
  ///
  /// `fileKey` is the 32-byte K_file: freshly generated by the sender,
  /// or recovered by the recipient from `wrapped_key` (app mode) or the
  /// URL fragment (link mode).
  static SuiteKeys derive(
    Sodium sodium,
    Uint8List fileKey,
    CryptoSuite suite,
  ) {
    switch (suite) {
      case CryptoSuite.classical:
        // Same key to both primitives — what suite 1 shipped. Kept so
        // transfers created before suite 2, and any in flight across a
        // deploy, still open.
        return SuiteKeys._(headerKey: fileKey, bodyKey: fileKey);
      case CryptoSuite.classicalSplitKeys:
        final master = SecureKey.fromList(sodium, fileKey);
        try {
          final header = sodium.crypto.kdf.deriveFromKey(
            masterKey: master,
            context: kdfContext,
            subkeyId: _headerSubkeyId,
            subkeyLen: sodium.crypto.secretBox.keyBytes,
          );
          final body = sodium.crypto.kdf.deriveFromKey(
            masterKey: master,
            context: kdfContext,
            subkeyId: _bodySubkeyId,
            subkeyLen: sodium.crypto.secretStream.keyBytes,
          );
          try {
            return SuiteKeys._(
              headerKey: header.extractBytes(),
              bodyKey: body.extractBytes(),
            );
          } finally {
            header.dispose();
            body.dispose();
          }
        } finally {
          master.dispose();
        }
    }
  }
}
